# Generated by Django 3.2.8 on 2021-10-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20211028_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='State'),
        ),
    ]
